# Generated by Django 4.1.5 on 2023-01-23 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('main_url', models.CharField(max_length=255)),
                ('shrtened_ur', models.CharField(max_length=255, unique=True)),
                ('total_views', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('edit_password', models.IntegerField()),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-createdAt'],
            },
        ),
    ]
